---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-react
  template:
    metadata:
      labels:
        app: eks-react
    spec:
      containers:
        - name: eks-react
          image: luke-h1/eks-react:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: eks-react-service
spec:
  selector:
    app: eks-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
